create table if not exists public.landing_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('regular', 'adult')),
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists landing_comments_mode_created_at_idx
  on public.landing_comments (mode, created_at desc);

alter table public.landing_comments enable row level security;
revoke all on table public.landing_comments from anon, authenticated;

create or replace function public.get_landing_comments(p_mode text)
returns table (
  id bigint,
  display_name text,
  body text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if lower(coalesce(p_mode, '')) not in ('regular', 'adult') then
    raise exception 'Invalid landing page mode';
  end if;

  return query
  select
    lc.id,
    coalesce(nullif(p.display_name, ''), 'Player') as display_name,
    lc.body,
    lc.created_at
  from public.landing_comments lc
  left join public.profiles p on p.id = lc.user_id
  where lc.mode = lower(p_mode)
  order by lc.created_at desc
  limit 40;
end;
$$;

create or replace function public.post_landing_comment(p_mode text, p_body text)
returns table (
  id bigint,
  display_name text,
  body text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_mode text := lower(coalesce(p_mode, ''));
  v_body text := btrim(coalesce(p_body, ''));
  v_id bigint;
  v_created_at timestamptz;
begin
  if v_user_id is null then
    raise exception 'Sign in to leave a comment';
  end if;

  if v_mode not in ('regular', 'adult') then
    raise exception 'Invalid landing page mode';
  end if;

  if char_length(v_body) < 1 or char_length(v_body) > 500 then
    raise exception 'Comment must be between 1 and 500 characters';
  end if;

  if exists (
    select 1
    from public.landing_comments lc
    where lc.user_id = v_user_id
      and lc.created_at > now() - interval '15 seconds'
  ) then
    raise exception 'Please wait a few seconds before posting again';
  end if;

  insert into public.landing_comments (user_id, mode, body)
  values (v_user_id, v_mode, v_body)
  returning landing_comments.id, landing_comments.created_at
  into v_id, v_created_at;

  return query
  select
    v_id,
    coalesce(nullif(p.display_name, ''), 'Player') as display_name,
    v_body,
    v_created_at
  from public.profiles p
  where p.id = v_user_id;

  if not found then
    return query select v_id, 'Player'::text, v_body, v_created_at;
  end if;
end;
$$;

revoke all on function public.get_landing_comments(text) from public;
revoke all on function public.post_landing_comment(text, text) from public;
grant execute on function public.get_landing_comments(text) to anon, authenticated;
grant execute on function public.post_landing_comment(text, text) to authenticated;