import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const headers = { "Access-Control-Allow-Origin": "https://metatim89-a11y.github.io", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Content-Type": "application/json" };
type Card = { r:number; s:string };
type Player = { id:string; name:string; seat:number; stack:number; bet:number; total:number; folded:boolean; allIn:boolean; hand:Card[]; bot:boolean };
type State = { phase:string; deck:Card[]; board:Card[]; players:Player[]; dealer:number; actor:number; currentBet:number; pending:number[]; pot:number; message:string; hand:number; smallBlind:number; bigBlind:number; smallBlindSeat:number; bigBlindSeat:number; buyIn:number };

const shuffle = () => {
  const deck:Card[]=[]; for(const s of ["S","H","D","C"]) for(let r=2;r<=14;r++) deck.push({r,s});
  for(let i=deck.length-1;i>0;i--){ const b=new Uint32Array(1);crypto.getRandomValues(b);const j=Math.floor(b[0]/4294967296*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]; }
  return deck;
};
const next = (from:number,p:Player[],ok:(x:Player)=>boolean) => { for(let n=1;n<=p.length;n++){const i=(from+n)%p.length;if(ok(p[i]))return i;}return -1; };
const pay=(p:Player,n:number)=>{const x=Math.min(p.stack,n);p.stack-=x;p.bet+=x;p.total+=x;p.allIn=p.stack===0;return x;};
const values=(cards:Card[])=>cards.map(c=>c.r).sort((a,b)=>b-a);
const rank5=(c:Card[])=>{const v=values(c),u=[...new Set(v)],w=u.includes(14)?[...u,1]:u;let st=0;for(let i=0;i<=w.length-5;i++)if(w[i]-w[i+4]===4){st=w[i];break;}const fl=c.every(x=>x.s===c[0].s);const g=u.map(x=>[v.filter(y=>y===x).length,x]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]);if(fl&&st)return[8,st];if(g[0][0]===4)return[7,g[0][1],g[1][1]];if(g[0][0]===3&&g[1][0]===2)return[6,g[0][1],g[1][1]];if(fl)return[5,...v];if(st)return[4,st];if(g[0][0]===3)return[3,g[0][1],...g.slice(1).map(x=>x[1])];if(g[0][0]===2&&g[1][0]===2)return[2,Math.max(g[0][1],g[1][1]),Math.min(g[0][1],g[1][1]),g[2][1]];if(g[0][0]===2)return[1,g[0][1],...g.slice(1).map(x=>x[1])];return[0,...v];};
const best=(c:Card[])=>{let b:number[]=[];for(let a=0;a<c.length-4;a++)for(let d=a+1;d<c.length-3;d++)for(let e=d+1;e<c.length-2;e++)for(let f=e+1;f<c.length-1;f++)for(let g=f+1;g<c.length;g++){const q=rank5([c[a],c[d],c[e],c[f],c[g]]);if(!b.length||cmp(q,b)>0)b=q;}return b;};
const cmp=(a:number[],b:number[])=>{for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d;}return 0;};
const names=["High Card","One Pair","Two Pair","Three of a Kind","Straight","Flush","Full House","Four of a Kind","Straight Flush"];
const publicState=(s:State,userId:string)=>({...s,deck:undefined,players:s.players.map(p=>({...p,hand:p.id===userId||s.phase==="SHOWDOWN"&&!p.folded?p.hand:p.hand.map(()=>null)}))});

const startHand=(old:State)=>{const p=old.players.map(x=>({...x,bet:0,total:0,folded:x.stack<old.bigBlind,allIn:false,hand:[]}));const active=p.filter(x=>!x.folded);if(active.length<2)return{...old,phase:"SHOWDOWN",message:"Not enough funded seats."};const dealer=next(old.dealer,p,x=>!x.folded),sb=active.length===2?dealer:next(dealer,p,x=>!x.folded),bb=next(sb,p,x=>!x.folded),deck=shuffle();let at=sb;for(let pass=0;pass<2;pass++)for(let n=0;n<active.length;n++){p[at].hand.push(deck.pop()!);at=next(at,p,x=>!x.folded);}pay(p[sb],old.smallBlind);pay(p[bb],old.bigBlind);const pending=p.map((x,i)=>!x.folded&&!x.allIn?i:-1).filter(i=>i>=0);return{...old,phase:"PREFLOP",deck,board:[],players:p,dealer,smallBlindSeat:sb,bigBlindSeat:bb,actor:next(bb,p,x=>!x.folded&&!x.allIn),currentBet:p[bb].bet,pending,pot:p.reduce((n,x)=>n+x.total,0),message:`Blinds ${old.smallBlind}/${old.bigBlind}`,hand:old.hand+1};};
const showdown=(s:State)=>{while(s.board.length<5){s.deck.pop();s.board.push(s.deck.pop()!);}const ranks=new Map(s.players.filter(p=>!p.folded).map(p=>[p.id,best([...p.hand,...s.board])]));const levels=[...new Set(s.players.map(p=>p.total).filter(n=>n>0))].sort((a,b)=>a-b);let prior=0;const won=new Set<string>();for(const level of levels){const involved=s.players.filter(p=>p.total>=level),eligible=involved.filter(p=>!p.folded);const pot=(level-prior)*involved.length;prior=level;if(!eligible.length)continue;eligible.sort((a,b)=>cmp(ranks.get(b.id)!,ranks.get(a.id)!));const winners=eligible.filter(p=>cmp(ranks.get(p.id)!,ranks.get(eligible[0].id)!)===0);let remainder=pot%winners.length,share=Math.floor(pot/winners.length);for(const w of winners){w.stack+=share+(remainder-->0?1:0);won.add(w.id);}}const winners=s.players.filter(p=>won.has(p.id));const top=winners[0]&&ranks.get(winners[0].id);s.phase="SHOWDOWN";s.actor=-1;s.message=`${winners.map(x=>x.name).join(" & ")} win${top?` with ${names[top[0]]}`:""}`;return s;};
const advance=(s:State)=>{s.players.forEach(p=>p.bet=0);s.currentBet=0;if(s.phase==="PREFLOP"){s.deck.pop();s.board.push(s.deck.pop()!,s.deck.pop()!,s.deck.pop()!);s.phase="FLOP";}else if(s.phase==="FLOP"){s.deck.pop();s.board.push(s.deck.pop()!);s.phase="TURN";}else if(s.phase==="TURN"){s.deck.pop();s.board.push(s.deck.pop()!);s.phase="RIVER";}else return showdown(s);s.pending=s.players.map((p,i)=>!p.folded&&!p.allIn?i:-1).filter(i=>i>=0);s.actor=next(s.dealer,s.players,p=>!p.folded&&!p.allIn);return s;};
const act=(s:State,userId:string,action:string,raiseTo=0)=>{const i=s.actor,p=s.players[i];if(!p||p.id!==userId)throw new Error("It is not your turn");const call=Math.max(0,s.currentBet-p.bet),before=s.currentBet;if(action==="fold")p.folded=true;else if(action==="all-in"){pay(p,p.stack);if(p.bet>s.currentBet)s.currentBet=p.bet;}else if(action==="raise"){if(raiseTo<s.currentBet+s.bigBlind)throw new Error("Raise is too small");if(raiseTo>p.bet+p.stack)throw new Error("Not enough chips");pay(p,raiseTo-p.bet);s.currentBet=p.bet;}else if(action==="call")pay(p,call);else if(action==="check"){if(call)throw new Error("You cannot check facing a bet");}else throw new Error("Invalid action");s.pending=s.pending.filter(x=>x!==i);if(s.currentBet>before)s.pending=s.players.map((x,n)=>n!==i&&!x.folded&&!x.allIn?n:-1).filter(n=>n>=0);s.pot=s.players.reduce((n,x)=>n+x.total,0);if(s.players.filter(x=>!x.folded).length===1){const w=s.players.find(x=>!x.folded)!;w.stack+=s.pot;s.phase="SHOWDOWN";s.actor=-1;s.message=`${w.name} wins`;return s;}if(!s.pending.length)return advance(s);s.actor=(i+1)%s.players.length;while(!s.pending.includes(s.actor))s.actor=(s.actor+1)%s.players.length;return s;};
const runBots=(s:State)=>{let guard=0;while(s.phase!=="SHOWDOWN"&&s.players[s.actor]?.bot&&guard++<20){const bot=s.players[s.actor],call=Math.max(0,s.currentBet-bot.bet);s=act(s,bot.id,call?"call":"check");}return s;};

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers});try{
  const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!token)throw new Error("Authorization required");
  const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!),{data:{user}}=await db.auth.getUser(token);if(!user)throw new Error("Invalid session");
  const body=await req.json(),tableId=body.tableId,{data:seat}=await db.from("holdem_table_seats").select("seat_number").eq("table_id",tableId).eq("user_id",user.id).maybeSingle();if(!seat)throw new Error("Join this table first");
  let{data:game}=await db.from("holdem_server_games").select("state,version").eq("table_id",tableId).maybeSingle();
  if(body.action==="start"){
    const{data:t}=await db.from("holdem_tables").select("*,holdem_table_seats(*)").eq("id",tableId).single();if(t.owner_id!==user.id)throw new Error("Only the owner can start");
    const humans=t.holdem_table_seats.map((x:any)=>({id:x.user_id,name:x.display_name,seat:x.seat_number,stack:t.buy_in,bet:0,total:0,folded:false,allIn:false,hand:[],bot:false}));for(let i=humans.length;i<t.max_players;i++)humans.push({id:`bot-${i}`,name:`CPU ${i+1}`,seat:i,stack:t.buy_in,bet:0,total:0,folded:false,allIn:false,hand:[],bot:true});
    const state=runBots(startHand({phase:"SETUP",deck:[],board:[],players:humans,dealer:-1,actor:-1,currentBet:0,pending:[],pot:0,message:"",hand:0,smallBlind:t.small_blind,bigBlind:t.big_blind,smallBlindSeat:-1,bigBlindSeat:-1,buyIn:t.buy_in}));game={state,version:1};await db.from("holdem_server_games").upsert({table_id:tableId,state,version:1});await db.from("holdem_tables").update({status:"playing"}).eq("id",tableId);
  }else if(body.action!=="state"){
    if(!game)throw new Error("Game has not started");if(body.expectedVersion!==undefined&&body.expectedVersion!==game.version)throw new Error("Table changed; action was not accepted");
    if(body.action==="buy-in"){if(game.state.phase!=="SHOWDOWN")throw new Error("Buy-ins are available between hands");const p=game.state.players.find((x:Player)=>x.id===user.id);if(!p||p.stack>=game.state.bigBlind)throw new Error("Buy-in is not available");p.stack=game.state.buyIn;p.folded=false;
    }else game.state=runBots(body.action==="next"?startHand(game.state):act(game.state,user.id,body.action,body.raiseTo));
    const previous=game.version;game.version++;const{data:updated}=await db.from("holdem_server_games").update({state:game.state,version:game.version,updated_at:new Date().toISOString()}).eq("table_id",tableId).eq("version",previous).select("version");if(!updated?.length)throw new Error("Another action arrived first; reload the table");
  }
  if(!game)throw new Error("Game has not started");const view=publicState(game.state,user.id);await db.from("holdem_game_snapshots").upsert({table_id:tableId,version:game.version,state:{phase:view.phase,message:view.message},updated_at:new Date().toISOString()});return new Response(JSON.stringify({state:view,version:game.version}),{headers});
}catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:"Request failed"}),{status:400,headers});}});
